version: "3.9"

services:
  mario_kart:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/usr/src/mario_kart
    env_file:
      - .env
    command: npm run start

  json-server:
    image: node:20-alpine
    container_name: json-server
    working_dir: /data
    volumes:
      - .:/data
    command: sh -c "npm install -g json-server && json-server --host ${JSON_SERVER_HOST} --port ${JSON_SERVER_PORT} db.json"
    env_file:
      - .env
    ports:
      - "${JSON_SERVER_PORT}:${JSON_SERVER_PORT}"
